version: "3.2"

services:

  auth-service:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    image: "auth-service:latest"
    restart: always
    depends_on:
      - userService
      - redis
    environment:
      - USER_SERVICE=user-service
      - REDIS_HOST=redis
    links:
      - "user-service:userService"
      - "postgres:db"


  user-service:
    build:
      context: .
      dockerfile: apps/users/Dockerfile
    image: "user-service:latest"
    restart: always
    depends_on:
      - postgres
    ports:
      - 8001:8000
    environment:
      - POSTGRES_HOST=postgres


  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lts
    ports:
      - '5432:5432'

  redis:
    image: redis
    restart: always
    ports:
     - "6379:6379"
