version: "3.8"

services:

  auth-service:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    image: "auth-service:latest"
    restart: always
    depends_on:
      - user-service
    environment:
      - USER_SERVICE=user-service
      - REDIS_HOST=lts-redis-do-user-6758097-0.b.db.ondigitalocean.com
      - REDIS_PORT=25061
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=eq2fjwjgvlr1d2v0
    ports:
      - 8005:8005

  user-service:
    build:
      context: .
      dockerfile: apps/users/Dockerfile
    image: "user-service:latest"
    restart: always
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=lts-db-server-do-user-6758097-0.b.db.ondigitalocean.com
      - POSTGRES_USER=doadmin
      - POSTGRES_PASSWORD=e4h6w5wexnw3qwhf
      - POSTGRES_PORT=25060
      - POSTGRES_DB=users-db
      - image-upload=image-upload

  file-upload:
    build:
      context: .
      dockerfile: apps/file-upload/Dockerfile
    image: "image-upload:latest"
    restart: always
    ports:
      - 8006:8006
    environment:
      - POSTGRES_HOST=lts-db-server-do-user-6758097-0.b.db.ondigitalocean.com
      - POSTGRES_USER=doadmin
      - POSTGRES_PASSWORD=e4h6w5wexnw3qwhf
      - POSTGRES_PORT=25060
      - POSTGRES_DB=file-db
      - DENO_PORT=8006

networks:
  app-network:
    driver: bridge